
export const songs = [
  {
    id: "1",
    title: "Shape of You",
    img: "./assets/img1.jpeg",
    artist: "Ed Sheeran",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "2",
    title: "Blinding Lights",
    img: "./assets/img2.jpeg",
    artist: "The Weeknd",
    genre: "Synthwave",
    src: "./assets/climax.mp3",
  },
  {
    id: "3",
    title: "Levitating",
    img: "./assets/img3.jpeg",
    artist: "Dua Lipa",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "4",
    title: "Peaches",
    img: "./assets/img4.jpeg",
    artist: "Justin Bieber",
    genre: "R&B",
    src: "./assets/climax.mp3",
  },
  {
    id: "5",
    title: "Save Your Tears",
    img: "./assets/img5.jpeg",
    artist: "The Weeknd",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "6",
    title: "Good 4 U",
    img: "./assets/img6.jpeg",
    artist: "Olivia Rodrigo",
    genre: "Pop Rock",
    src: "./assets/climax.mp3",
  },
  {
    id: "7",
    title: "Montero",
    img: "./assets/img7.jpeg",
    artist: "Lil Nas X",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "8",
    title: "Kiss Me More",
    img: "./assets/img8.jpeg",
    artist: "Doja Cat",
    genre: "R&B",
    src: "./assets/climax.mp3",
  },
  {
    id: "9",
    title: "Bad Habits",
    img: "./assets/img1.jpeg",
    artist: "Ed Sheeran",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "10",
    title: "drivers license",
    img: "./assets/img2.jpeg",
    artist: "Olivia Rodrigo",
    genre: "Pop",
    src: "./assets/climax.mp3",
  },
  {
    id: "11",
    title: "Stay",
    img: "./assets/img3.jpeg",
    artist: "The Kid LAROI",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "12",
    title: "Butter",
    img: "./assets/img4.jpeg",
    artist: "BTS",
    genre: "Pop",
    src: "./assets/climax.mp3",
  },
  {
    id: "13",
    title: "Deja Vu",
    img: "./assets/img5.jpeg",
    artist: "Olivia Rodrigo",
    genre: "Pop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "14",
    title: "Positions",
    img: "./assets/img6.jpeg",
    artist: "Ariana Grande",
    genre: "R&B",
    src: "./assets/you-are-my-hope.mp3",
  },
  {
    id: "15",
    title: "Heat Waves",
    img: "./assets/img7.jpeg",
    artist: "Glass Animals",
    genre: "Indie Rock",
    src: "./assets/lofi.mp3",
  },
  {
    id: "16",
    title: "Levitating (feat. DaBaby)",
    img: "./assets/img8.jpeg",
    artist: "Dua Lipa",
    genre: "Pop",
    src: "./assets/you-are-my-hope.mp3",
  },
  {
    id: "17",
    title: "Mood",
    img: "./assets/img1.jpeg",
    artist: "24kGoldn",
    genre: "Hip-Hop",
    src: "./assets/lofi.mp3",
  },
  {
    id: "18",
    title: "Goosebumps",
    img: "./assets/img2.jpeg",
    artist: "Travis Scott",
    genre: "Hip-Hop",
    src: "./assets/you-are-my-hope.mp3",
  },
  {
    id: "19",
    title: "Dance Monkey",
    img: "./assets/img3.jpeg",
    artist: "Tones and I",
    genre: "Alternative/Indie",
    src: "./assets/lofi.mp3",
  },
  {
    id: "20",
    title: "Rockstar",
    img: "./assets/img4.jpeg",
    artist: "DaBaby",
    genre: "Hip-Hop",
    src: "./assets/you-are-my-hope.mp3",
  },
];